dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notification:
  slack:
    rooms:
      secure: PcxZYzrPGpgy3vapUKnm+TB8n9atYfOVXGaKMKOrRi157PMtHPsBYTzTX71jHQVZWdsRx15gCBSVOMzOt8H8Iasu2if9p6y9YlRufA41j0E+ZEefPLjNrL2HqKzB3O0hBd7SVSC6AhX+nG7SF9deHn5V9ZkIHmSjbe3ALCN+adYMgyOfJMBra7uOq0Kr58E+pJTB8zu/b3VTilXgfi4WuUI+YuzybjG0DhYueauyniyBGe3DB7qDwbaXBfQjU1yqu7ITL6g4+RUmwczAEqdm4AMFtiGGmDUpW4uC2Su7LBy4ARvyKNY1iI5WBwbkwMGeWc6gAotVLMAd21azsyYnWzH6sjrwIGJJtZF6svuQb+3wd5GfFijKrTm+0fexx4IWdXBYIyzUsQcOgbFOSDTV/T2bGKjFeScD/Hhqbh8XD4NWtid1DM8xPBXxW7iOLICRrSkCFQ5cZFfY0jImR+TcgMUUL2sGVhib6svveYIskOy6IovQ1PKXh/1fCsbln12KXrdjmoMTg7rkosXGZQz63aA6EeYbEgwrBMgnitGETG5X69dg9Yg/3BGDpM2GyEeyvfYqcwmxpMfzLfxdiFL0c7O4fOi4xV+xi2ZzwLafDksSgz7WCfZurXvulNfxgM7MTS9pduswHnZ7bfCHjPfDfc62dwEae0EOG6W53QzHi4I=
