dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notification:
  slack:
    rooms:
      secure: uUHUezmztDvyqri9JnTTgJ+N+ctoH/dBukCSxOFW0icHvUdN4/hHHGsJUiDXZXflGeJu240Zzn06MyeoSuSiZxbED8sidmCRYYqkIPJJFtXCUmj+jfy/P1ybjSB2XlaSR1NkNHfMgQBTkzl9AnswjvTBr3OCLy9fdKlHPfr318nrtYmJD9rKhbaN3021IGLPRMKBx6hDq9mc5Zgie66oH2QKiBFnkVEUUAmnAx9TKrpbl2RFBTGWHmMAUCG2+1XMvGJKFKYiWgEKEJgdSpNJDKrPhNxlviV3pr0m7MByYUf2e7mMDcmxNxwti/xH3iPUXEYTNZNZAXpgetc1i6EhuBbWDnfqfD9gMq7X3UeX83D3Wq8dWFOwbBWf1JEUn0e9GHcXe6oZc/DWm+0cCaeMl4KEdAMDWuC5/K6hLnRAi39jhuyPN/GpwOdBqeCI7YY+c8J9qAl6CUhg6PZ0eQUlrdE7c6Mdcz0bZyPCZbVGCIbSZ6big5Pr9z82P8hLqIjB5Pbc42QRUZa33G6geW1C1bX7ptl9la1P2SpwSm95g1SaarFB/DGtz4Ieh4FL1A4lbQiDRIrtv+Pi7JScJDilnPi+KrDbrTeHCjeknzMYm6QsTVe8AnkWkNFMVrd5pccIRKzHaZHpOT/pbKUi6aQ8Lub7K4HZ/oqgOjtk0ESRFX4=
