dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notification:
  slack:
    rooms:
      secure: ZBYuEkn3jAzMVCf9W/3hgAIjHTk68rz/sKP+XY92oWXcQT8Qbn1i+myDBIAxpNpnDBJZ2FdwraOF/JX4Vm+Pq1hDsTt4G/V7Ta+EAb/GAsx1WEZqg8RBU9I49vZ7fVhbxZjU5UjVgXB6/PHF1cuTXO4ilXm0ev1BAfJk87B02Lu1ZS/ExzUYGr1xuqUtrtb+ltf6TR5zXjO3jVrAkJngyiapMhyzwve1G8TbjtHeSxxHEU6h0amEi2HMi0888k7bDItlLQMsJJKhyn4bTmwPztp9Cnf54Bpeq0DnPwKQj//J+BqCVyeiw9TuTZiydZz1Qht6ssXvRQTCFAP9k6QLR6IAcQFebo57ulVALdoQWz6GmOlonnezQG8ZI6/6I87bhCnR0SYfav5fW4WknMZ6WDPb4QJeoEw/DwUXC7pAXNjsg147ywXQd9W6I1qGRtJ9wC/aU3QlJQYuhy6603CnQPsnWG5kt2dJk8RDQesKy+ZyKFglt486mS1SHyC7ikTEEe8UqujK3FDGMSpjvy/4DX1H3J/R+uo52w7AgrBQ6hqxzkbO2f2XkIL+YODNQZ05TwezQP28kCJdwd1HBixMbrVFIGv9pvzb8AWCWECCPJmzJ99v0TdazmgZgumPPteVo4HNaHxL/FyA1maKn8TPpofAap0CkylxjEOo443Rwmo=
