dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notification:
  slack:
    rooms:
    secure: "lVf+j+GdvcSrKxa/HK/Vc8rYmacfWGdycM34lNMeSTkvxeELz39Ad7P/zLC3Y+rllrNo54pXf8ZACWh3XDueQOijeN5gBAcj2FyaDuuGXOSPt1ClQRakbdT6kiYsWOTm2BSIe5X0TujUiS3Tkj9qZFQXOx4Q/t4W9vkm3MovxATnIYPVQ8xwEiKwjBN8LC67QHbg9GeOfzg7f3IN3hDuv2bjyeo6II74h7NJoLcvs5samS+/ZHlgHMdaICJbuqO8fB4cLT/bWx3cJMDeE6NmBH9X7eT/RoLl8SeFnhlxkfliIPqnjhy6G9yUBd0EMGNigtUIlpBypXCw3SoUVX3RR+DN498UREgHntHdUL5Ke8EL2o4xT/7E3BULWo1GwyKg9+SwXIkTbH/5Q4q5z6JIrc/SSEMzFuEfNExPCpdaGvqH6ATkO7jcY6+IIxCxOnqlC1OMpgPeZr8hB7Hy/3BldlJy1+9p5+qVLi8SjolnE9vSXKJQ68GXFtUnAnRD296wgGnWM2fuuu9AP4HHj2W1/If04Fwg7VH/29eDpB1hHaN9iiO2ECquV9AohJkfrUF6sL3RwzbA4KjXw0V/4xTlaIBjW32rXm4VmAs+/OQNHu3Qkdp+tGtQNo97ZvymeDqK084plZMpfY1HSzLdcQ+tN0WWmNy3KJZd+Ja1q4T9mnA="
      on_success: always
