dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notification:
  slack:
    rooms:
      secure: MnUpWPFKM7DwjRS0qsevKalF1sOL2aewEkXoQY6ot/SDXnVqe+V9cmKJI3VPn0ABvdwvjqGHL6YZYlshP9kg3KZIoolI8OQTtMRVJjfULtRJicjdRDmdAQYixJBIC85XtLvnoL9jb9MGP+CntUtNgdhDUjjc0r3Fuz7IopPL/XuNPpWMlKRenX0twAal7OhSVlwNJDLqlmyskixnidC4AnG0xIAvZbLlGhYKQBYc6S1kTF/ha2opkaCfD6BgisL3L3EnIJ1bhnw6KqoFpp4ZezdM9YN7NIZTNQPOaBbKFPeHQABKzCfeLF54JxacoeXtrLBZ0iq3Xo5UygNT17AH3W6tQmE9jXxdorEl7cyf6p1qedIPItx+HOkA8lc/3fNcjMwSMea66qoqrjgmL+6EvET2IhDAc60ZFRfvHCO+6nbDDb/C6OPgsZUaPeaK76tulzrJW67DqR2+eXB9WifVRyN/tOK/A3PgKq7k54WqN3O8kktNbBefPgIV4I4EjErhBxbKZZbXznq970ABn6lPcoQNo6EQp/NRMcMbPOcV7bip2To3qSdAH2CFKEjmUtrfvhIEJ+XEwTAtTYms2fVW0cdeRHsCNSrXuvSjG92liZt7EmKVxZxrzL89Zrw/uQrIiNf0HlAwTij8pVjr5gwAJl6eE7DYaF4uYeyZv/TF2IM=
