dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notification:
  slack:
    rooms:
      secure: MMIfH9/GWb80VGVxp0bonT0PbOrC+ntBXWb3+DbcFIBzr2LZr7C7IaBQEdG0lMVUFviEl4LIyjk/WUfQ+mnazKa43gJ3lFC0yanZefyVPiJymWyZUl4v65IYl8vGm02Q9zRpeABYqIYo7ncWbUhc7VwMmyl7PugUe9Nf3jokXoqD83UFiUXEfCUCGic/ptKdvvJ7Wz65SD6fLUz9oW3ty/Sqp6s4BbvIOeO/H60LZWId4ThYR5krTDKEn5WbpD5HWtSnfccxYG1AGCOlBDmWXZ9wedp1gXzu79tadrq87Zr175f/iuPHN1kYBCNHVaLfUOpX6A2GU5XLiKJFqrNyOjzeQhw+QKX3sNm3ASzkCRph2r6xHgC5fygfA3aCnK4ryplMCTp5SbpL2sjcE2MCVs/Pdxb3cN6wltlQXFSDMCx83ex9YMnHPR2lNmlcl+kijAOX+AqaFxpcLMktBtFEQAHO5Ns0OfH3J6QCLKJf0cOYoG350BNMtUNvQNRlQUxmNeTRNGpf/txySQylKb4WDtFrjzuJOABcysDHHJYxjJZDyjA32sJpP3HoKymC4WXffL8v8mfUsM01c9cvD/R760yZq/+4C/URyLRkHnv2O3VC+CK2bJSC8/RVlEAOMD+cA8gpj+op2Gom22aopA/4BQaJqCP7WdVyx26XoxqBb1I=
