dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notification:
  slack:
    rooms:
      secure: r6xv+yi2Tz2Gpk1PsBG2bimzvldLdtJnvc2pp77FHpMSFZsMc44f3I/weQhroJc+X0w/dXnNYKJ/8LGg3dxdUw6VryKY07QjAqjtxiI/G0j3V9FB2Op3qgk8mrZK8R6+4OIdjT5vFDRUmhpSOKYiSo0WVuXQ6tfmdeZFuAETI2orcSFdY9yiLZTmn4sPvu03NP8PV8oGi873UxG+NpFlT8UQ5tki5vNv9xafaFGuHW73O/qMZbX64c7SLhD68XUwOoMM1CC2eZpkiyEvndGRYfkDeKkjy5Nbx7PQJTg2j9Bv9hUcaO+ZxoSnfvoCv9jrem3Xp1tCUh3rqisnK/jEpYgZ3ovGiSKxL8Xk+V2lpaTURGuT5MtuGix+Jx8SjpcDCXQY1N4bPI1QOf/pf/wgx+QeRgLMaz4WVnLfPSz96DBvYrSKUoYEbFA8FR6mTZKvLAMudNDj1CKAuI0aDuVwlUaPnVb4A9rVL5QgE9C3yFZzmhfuQ/gSas2FMnW6OYrffWsMLct0lIXPPgDc4d1FvCC8CfAF/UKQJSA0hW8prDLoQrB8khTgO7J2pGeM+jijqQRivMsHjNpSTUuinhxQ+AbtHpvtpmCvm/QfZmwtMHqM683LTis4ekjGUoFHviU0ZgMk+KZnymLWsK94jTbtBppm28NxV+08uAbKse4pyBc=
