dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notification:
  slack:
    rooms:
      secure: "eIZg/Bwr20OzaUqG1/Yjj/ROe6/lY9PTerji1NXgzPoBCXak0ImmbOex/kNqYc66RKsBYRXGW40AhMkfmylhyuoHmzLWOGcnc7SlKhvFCwmJfXdBaZ3Wuys1FPiqT26o8SCTVfE34Ea0er4nwe3Y2Wqw+QUuGYneBIGpr+poEBcyKDSX1hUSavSUFA49hPD8OV4YaK91RANlXXOQg7mQqK9vB0hhTEzvSgn8SdsouNQlPxxApLLpNXheBOmtw60+aACTkbg9uDfYJr498276D8Mq6Jzc0Z3+LxXs5rtIKqF/RGbsN1psSW2Vro6rJCOA+E1TPql4+RgL9TApmkdIoPK39OQqxtqOrMjYe4P5eEPZYrJihlet5wite7Qq9WfjP9ER1VYtqS6BBI8gnEsO8PkNQN/IEDCxR3xQ18hERgIz+nMTJX1y/gL6eHX/O2ueLObzBNUTJ3UXa+xYcqkEkG2NclPJ0tJpG3jTBowCxIn9qbZ3KkBrzlqpO90amvc/KlhU+lkDlkZhhVSNJ6ghzceORTwYndVlff8mwz3DdZfCLoSsmHfekAWvPFpark4JfrvwuydbHEQPbdwHTlOC5Fql6Hu9Oj5CMQEwzljJpQlfiw+tOf/wIQQCy5IcwG9vzzcpz+RAOM7qMZ1990+Ay+3EaR1VwscqBoRzv0v/VPk="
      on_success: always
