dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notification:
  slack:
    rooms:
      secure: 1ncV0rciGN1ncZwpTTRF+s8aHk+aLKSOKNq0p9Y0pTXjddrfTuhyC8hkEaRWnOEy/umOPql82JOO6deCcG8rEsC0yk+qxRjq5xG+KPXpUZeRKJ9BeIFRRNtZUhxpFf7NjUbXkGiVw6FL70jndQ//iT0+fKvDSaSOtVhYX+FkyugE1PpsUyxhe7eWvf40ItFOk+Nd0HPE8syvneUo6D4w9qFGkMp0wwNe3KJXgMrnEz2xxrxfkShoy1FMfpP5H4E6Y8evGc3UvEd/w3Sekb26GusRiZjIa6jqWRtsAPfFlbPtwigGf4TMqsMhUm7gy1Eqre8EekVVY3HVTcIdOk3iWa5MjMBbNPTxMTlJzDOE/Bu71WTPM78u+0ubMPTSJGrxwvNJppvIOH7LQEScHOpBGU9pH9KIwjwsET6L5BUiRIbXVas7xbu540CU1xNVWMr9dBefC6cOfIqWI5dNHRM+gZ5iRkPPmUR0e736Cb1T0BtfyYtp/H35MgGCA8DjJJTzHBIXUvkZ8+Xyijq8bOJKbo7fv1afMsexatPJoiXm1fii0kwLKEuiyNAsuAWSHsiYU/XGk1bQs4sFanamRTsHIBlZckOCit7JSfYVp25VbcsDXord6Gy4qNTg9eQ1jSNkudK+auwNDUU9MpWN+2Tukfvg+hKI8rYRQcdNE7GI9Mw=
