---
- name: Configure MongoDB
  hosts: reddit-db
  become: true
  vars:
    mongo_bind_ip: 10.132.0.3
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongo.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted
