all:
  hosts:
    appserver:
      ansible_host: 35.241.255.10
    dbserver:
      ansible_host: 35.241.236.181
  children:
    app:
      hosts:
        appserver:
    db:
      hosts:
        dbserver:

