---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
  - name: Add MongoDB repo key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  - name: Add MongoDB repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install MongoDB
    apt:
      name: mongodb-org
      state: present

  - name: Configure MongoDB
    systemd:
      name: mongod
      enabled: yes